### ISSUE TITLE
异常的日志

### ISSUE THREAD

**Issue by baijin4422** [andandroidor/ourtv#45]
java.lang.RuntimeException: Unable to stop activity {com.cctv.yangshipin.app.androidp/com.cctv.yangshipin.app.androidq.ui.main.MainTVActivity}: java.lang.IllegalArgumentException: Receiver not registered: com.cctv.yangshipin.app.androidq.ui.main.VolumeChangeReceiver@ee617e5
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5624)
	at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5596)
	at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5665)
	at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:43)
	at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:190)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:101)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2574)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8711)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: com.cctv.yangshipin.app.androidq.ui.main.VolumeChangeReceiver@ee617e5
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1691)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1883)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:831)
	at com.cctv.yangshipin.app.androidq.ui.main.MainTVActivity.onStop(Native Method)
	at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1635)
	at android.app.Activity.performStop(Activity.java:9164)
	at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5616)
	... 14 more

**Comment by andandroidor** [comment]
收到，感谢反馈
